// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvO2KVd8mCu1bKciAYkV2eQmZoWR1FZrA',
    appId: '1:406668123199:web:b040c7511e4aa4270c6c8a',
    messagingSenderId: '406668123199',
    projectId: 'rentacar-1a61d',
    authDomain: 'rentacar-1a61d.firebaseapp.com',
    storageBucket: 'rentacar-1a61d.appspot.com',
    measurementId: 'G-BGQB9X0YF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSGqZefkdtAS9bt9avj1HoCx_q_S1VV70',
    appId: '1:406668123199:android:6d3887248b8452cd0c6c8a',
    messagingSenderId: '406668123199',
    projectId: 'rentacar-1a61d',
    storageBucket: 'rentacar-1a61d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ4ujs8YQwrT3kAL5GRCaJxvqBCbuq6Mc',
    appId: '1:406668123199:ios:dab22c8fd1be00540c6c8a',
    messagingSenderId: '406668123199',
    projectId: 'rentacar-1a61d',
    storageBucket: 'rentacar-1a61d.appspot.com',
    iosClientId: '406668123199-itoijerfl72iecem8ou7taf2lr1d3lfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentacar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ4ujs8YQwrT3kAL5GRCaJxvqBCbuq6Mc',
    appId: '1:406668123199:ios:dab22c8fd1be00540c6c8a',
    messagingSenderId: '406668123199',
    projectId: 'rentacar-1a61d',
    storageBucket: 'rentacar-1a61d.appspot.com',
    iosClientId: '406668123199-itoijerfl72iecem8ou7taf2lr1d3lfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentacar',
  );
}
